<?php

use Illuminate\Database\Seeder;

class stworzMiasta extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		DB::table('miasta')->insert([
				'miasto'=>'Aleksandrów Kujawski'
				]);
		DB::table('miasta')->insert([
				'miasto'=>'Andrychów'
				]);
		DB::table('miasta')->insert([
				'miasto'=>'Augustów'
				]);
		DB::table('miasta')->insert([
				'miasto'=>'Barlinek'
				]);
		DB::table('miasta')->insert([
				'miasto'=>'Bartoszyce'
				]);
		DB::table('miasta')->insert([
				'miasto'=>'Będzin'
				]);
		DB::table('miasta')->insert([
				'miasto'=>'Bełchatów'
				]);
		DB::table('miasta')->insert([
				'miasto'=>'Bełżyce'
				]);
		DB::table('miasta')->insert([
				'miasto'=>'Biała Podlaska'
				]);
		DB::table('miasta')->insert([
				'miasto'=>'Białogard'
				]);
		DB::table('miasta')->insert([
				'miasto'=>'Białystok'
				]);
		DB::table('miasta')->insert([
				'miasto'=>'Bielawa'
				]);
		DB::table('miasta')->insert([
				'miasto'=>'Bielsko-Biała'
				]);
		DB::table('miasta')->insert([
				'miasto'=>'Bielsk Podlaski'
				]);
		DB::table('miasta')->insert([
				'miasto'=>'Bieruń Lędziny'
				]);
		DB::table('miasta')->insert([
				'miasto'=>'Bierutów'
				]);
		DB::table('miasta')->insert([
				'miasto'=>'Biłgoraj'
				]);
		DB::table('miasta')->insert([
				'miasto'=>'Biskupiec'
				]);
		DB::table('miasta')->insert([
				'miasto'=>'Blachownia'
				]);
		DB::table('miasta')->insert([
				'miasto'=>'Błonie'
				]);
		DB::table('miasta')->insert([
				'miasto'=>'Bochnia'
				]);
		DB::table('miasta')->insert([
				'miasto'=>'Bogatynia'
				]);
		DB::table('miasta')->insert([
				'miasto'=>'Boguszów-Gorce'
				]);
		DB::table('miasta')->insert([
				'miasto'=>'Bolesławiec'
				]);
		DB::table('miasta')->insert([
				'miasto'=>'Bolków'
				]);
		DB::table('miasta')->insert([
				'miasto'=>'Braniewo'
				]);
		DB::table('miasta')->insert([
				'miasto'=>'Brodnica'
				]);
		DB::table('miasta')->insert([
				'miasto'=>'Brwinów'
				]);
		DB::table('miasta')->insert([
			'miasto'=>'Brzeg'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Brzeg Dolny'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Brzesko'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Brzeszcze'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Brzeziny'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Brzozów'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Bukowno'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Busko-Zdrój'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Bychawa'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Bydgoszcz'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Bystrzyca Kłodzka'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Bytom'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Bytów'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Chełm'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Chełmek'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Chełmno'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Chełmża'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Chocianów'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Chodzież'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Chojnice'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Chojnów'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Chorzów'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Choszczno'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Chrzanów'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Ciechanów'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Ciechocinek'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Cieszyn'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Czarne'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Czarnków'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Czechowice-Dziedzice'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Czeladź'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Czersk'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Czerwionka-Leszczyny'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Częstochowa'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Człuchów'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Dąbrowa Górnicza'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Dąbrowa Tarnowska'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Darłowo'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Dębica'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Dębica'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Dębno'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Długołęka'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Dobre Miasto'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Drawsko-Pomorskie'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Drezdenko'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Duszniki-Zdrój'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Działdowo'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Działoszyn'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Dzierzgoń'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Dzierżoniów'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Elbląg'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Ełk'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Garwolin'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Gdańsk'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Gdynia'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Giżycko'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Gliwice'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Głogów'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Głowno'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Głubczyce'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Głuchołazy'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Głuszyca'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Gniew'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Gniezno'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Goerlitz'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Gołdap'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Goleniów'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Golub-Dobrzyń'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Góra'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Góra Kalwaria'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Gorlice'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Gorzów Wielkopolski'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Gostyń'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Gostynin'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Grajewo'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Grodzisk Wielkopolski'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Grodzisk Mazowiecki'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Grójec'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Grudziądz'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Gryfice'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Gryfino'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Gryfów Śląski'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Gubin'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Hajnówka'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Hel'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Hrubieszów'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Iława'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Imielin'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Inowrocław'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Janów Lubelski'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Jarocin'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Jarosław'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Jasło'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Jastrowie'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Jastrzębie-Zdrój'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Jawor'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Jaworzno'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Jędrzejów'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Jelcz-Laskowice'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Jelenia Góra'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Józefów'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Kalety'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Kalisz'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Kamienna Góra'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Karczew'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Karpacz'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Kartuzy'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Katowice'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Kąty Wrocławskie'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Kazimierz Dolny'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Kędzierzyn-Koźle'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Kępno'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Kętrzyn'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Kęty'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Kielce'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Kłobuck'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Kłodawa'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Kłodzko'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Kluczbork'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Knurów'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Kobyłka'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Kolbuszowa'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Kolno'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Koło'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Kołobrzeg'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Koluszki'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Koniecpol'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Konin'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Końskie'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Konstancin-Jeziorna'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Kórnik'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Koronowo'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Kościan'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Kościerzyna'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Kostrzyn'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Kostrzyn nad Odrą'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Koszalin'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Kowary'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Kozienice'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Kozy'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Kraków'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Krapkowice'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Kraśnik'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Krasnystaw'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Krosno'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Krosno Odrzańskie'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Krotoszyn'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Krynica'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Krynica Morska'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Krzepice'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Krzeszowice'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Kudowa-Zdrój'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Kutno'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Kwidzyn'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Lądek-Zdrój'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Lębork'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Lędziny'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Legionowo'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Legnica'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Leszno'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Leżajsk'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Libiąż'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Lidzbark'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Lidzbark Warmiński'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Limanowa'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Lipno'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Lubaczów'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Lubań'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Lubartów'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Lubawa'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Lubawka'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Lubin'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Lublin'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Lubliniec'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Luboń'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Lubsko'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Lwówek Śląski'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Łańcut'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Łapy'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Łask'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Łaziska Górne'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Łazy'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Łeba'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Łęczna'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Łęczyca'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Łobez'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Łódź'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Łomianki'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Łomża'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Łowicz'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Łuków'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Maków Mazowiecki'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Maków Podhalański'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Malbork'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Marki'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Miasteczko Śląskie'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Miastko'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Miechów'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Międzychód'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Międzyrzecz'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Mielec'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Mikołów'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Milanówek'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Milicz'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Mińsk Mazowiecki'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Mogilno'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Mońki'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Morąg'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Mosina'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Mrągowo'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Mszana Dolna'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Murowana Goślina'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Myślenice'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Myślibórz'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Mysłowice'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Myszków'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Nakło nad Notecią'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Namysłów'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Nasielsk'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Nidzica'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Niepołomice'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Nisko'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Nowa Dęba'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Nowa Ruda'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Nowa Sól'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Nowe Miasto Lubawskie'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Nowogard'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Nowy Dwór Gdański'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Nowy Dwór Mazowiecki'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Nowy Sącz'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Nowy Targ'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Nowy Tomyśl'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Nysa'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Oborniki'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Oborniki Śląskie'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Ogrodzieniec'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Oława'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Olecko'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Oleśnica'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Olkusz'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Olsztyn'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Olsztynek'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Opalenica'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Opoczno'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Opole'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Opole Lubelskie'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Orneta'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Orzesze'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Ostróda'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Ostrołęka'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Ostrów Wielkopolski'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Ostrowiec Świętokrzyski'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Ostrzeszów'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Oświęcim'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Otwock'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Pabianice'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Pajęczno'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Parczew'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Pasłęk'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Pelplin'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Piaseczno'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Piechowice'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Piekary Śląskie'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Pieńsk'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Pieszyce'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Piła'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Piława Górna'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Pińczów'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Pionki'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Piotrków Trybunalski'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Pisz'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Pleszew'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Płock'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Płońsk'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Pniewy'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Pobiedziska'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Poddębice'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Polanica-Zdrój'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Police'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Polkowice'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Poniatowa'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Poręba'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Poznań'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Prabuty'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Proszowice'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Prudnik'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Pruszcz Gdański'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Pruszków'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Przasnysz'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Przemków'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Przemyśl'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Przeworsk'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Przysucha'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Pszczyna'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Pszów'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Puck'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Puławy'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Pułtusk'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Pyrzyce'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Pyskowice'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Rabka-Zdrój'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Racibórz'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Radlin'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Radom'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Radomsko'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Radzionków'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Radzymin'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Radzyń Podlaski'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Rawa Mazowiecka'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Rawicz'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Reda'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Rogoźno'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Ropczyce'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Ruda Śląska'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Rudnik nad Sanem'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Rumia'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Rybnik'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Rydułtowy'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Ryki'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Rypin'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Rzeszów'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Sandomierz'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Sanok'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Sędziszów Małopolski'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Siechnice'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Siedlce'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Siemianowice Śląskie'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Siemiatycze'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Sieradz'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Sierpc'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Siewierz'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Skarszewy'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Skarżysko-Kamienna'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Skawina'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Skierniewice'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Skoczów'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Skwierzyna'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Sławków'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Sławno'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Słubice'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Słupca'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Słupsk'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Sobótka'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Sochaczew'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Sokółka'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Sokołów Podlaski'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Solec Kujawski'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Sopot'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Sosnowiec'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Stalowa Wola'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Starachowice'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Stargard'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Starogard Gdański'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Stary Sącz'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Staszów'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Stronie Śląskie'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Strzegom'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Strzelce Krajeńskie'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Strzelce Opolskie'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Strzelin'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Strzyżów'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Sucha Beskidzka'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Sulechów'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Sulęcin'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Sulejów'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Sulejówek'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Sułkowice'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Suwałki'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Swarzędz'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Syców'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Szamotuły'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Szczawnica'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Szczawno-Zdrój'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Szczebrzeszyn'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Szczecin'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Szczecinek'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Szczekociny'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Szczyrk'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Szczytno'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Szklarska Poręba'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Szprotawa'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Sztum'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Szydłowiec'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Śrem'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Środa Śląska'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Środa Wielkopolska'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Świdnica'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Świdnik'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Świdwin'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Świebodzice'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Świebodzin'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Świecie'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Świeradów-Zdrój'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Świętochłowice'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Świnoujście'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Tarnobrzeg'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Tarnów'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Tarnowskie Góry'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Tczew'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Terespol'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Tomaszów Lubelski'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Tomaszów Mazowiecki'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Toruń'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Toszek'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Trzcianka'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Trzebiatów'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Trzebinia'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Trzebnica'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Trzemeszno'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Tuchola'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Tuchów'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Turek'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Tuszyn'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Twardogóra'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Tychy'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Ustka'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Ustroń'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Ustrzyki Dolne'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Wąbrzeźno'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Wadowice'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Wągrowiec'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Wałbrzych'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Wałcz'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Warka'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Warszawa'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Wasilków'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Węgorzewo'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Węgrów'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Wejherowo'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Wieliczka'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Wieluń'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Wieruszów'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Wisła'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Witkowo'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Władysławowo'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Włocławek'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Włodawa'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Włoszczowa'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Wodzisław Śląski'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Wojkowice'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Wolbrom'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Wołomin'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Wołów'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Wolsztyn'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Woźniki'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Wrocław'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Wronki'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Września'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Wschowa'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Wyszków'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Ząbkowice Śląskie'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Zabrze'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Zakopane'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Zambrów'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Zamość'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Zawiercie'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Zbąszyń'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Zduńska Wola'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Zdzieszowice'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Zelów'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Zgierz'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Zgorzelec'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Ziębice'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Zielona Góra'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Zielonka'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Złocieniec'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Złotoryja'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Złotów'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Żagań'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Żarki'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Żarów'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Żary'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Żmigród'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Żnin'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Żory'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Żukowo'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Żuromin'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Żychlin'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Żyrardów'
			]);
		DB::table('miasta')->insert([
			'miasto'=>'Żywiec'
			]);
    }
}
